version: '3.8'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: garmin_nginx
        ports:
            - "80:80"
        volumes:
            - './:/var/www/html'
            - './docker/nginx/dev.nginx:/etc/nginx/conf.d/default.conf'

        depends_on:
            - php
            - mysql
        networks:
            - garmin_laravel
    supervisor:
        container_name: garmin_supervisor
        build:
            context: ./docker/
            dockerfile: Supervisor.Dockerfile
            args:
                user: garmin
                uid: 1000
        image: laravel-8.2/supervisor
        restart: unless-stopped
        volumes:
            - '.:/var/www/html'
        networks:
            - garmin_laravel
        depends_on:
            - php
    php:
        container_name: garmin_php
        build:
            context: ./docker/
            dockerfile: Dockerfile
            args:
                user: garmin
                uid: 1000
        image: laravel-8.2/app
        ports:
            - "9000:9000"
        volumes:
            - '.:/var/www/html'
        networks:
            - garmin_laravel
        depends_on:
            - mysql
            - redis
        extra_hosts:
            - host.docker.internal:host-gateway
    mysql:
        container_name: garmin_mysql
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'garmin_mysql:/var/lib/mysql'
        networks:
            - garmin_laravel
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
    mysql_test:
        container_name: garmin_mysql_test
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'garmin_mysql_test:/var/lib/mysql'
        networks:
            - garmin_laravel
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping" ]
    redis:
        container_name: garmin_redis
        image: 'redis:latest'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'garmin_redis:/data'
        networks:
            - garmin_laravel
    npm:
        image: node:19.6
        container_name: garmin_npm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: [ 'npm' ]
        networks:
            - garmin_laravel
    phpmyadmin:
        image: arm64v8/phpmyadmin
        container_name: garmin_phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: secret
            PMA_HOST: mysql
            PMA_PORT: 3306
        restart: always
        depends_on:
            - mysql
        ports:
            - "8081:80"
        networks:
            - garmin_laravel
    mailpit:
        container_name: garmin_mailpit
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - garmin_laravel

networks:
    garmin_laravel:
        driver: bridge
volumes:
    garmin_mysql:
        driver: local
    garmin_mysql_test:
        driver: local
    garmin_redis:
        driver: local
